@startuml
User -> PrimaryFrame : Button Start
PrimaryFrame -> GameMenu

GameMenu -> MyArmy : CreateArmy
loop 4 times
MyArmy-> Factory : createUnit
MyArmy -> Director : build
Director -> UnitBuilder : buildHealth
Director -> UnitBuilder : buildStrength
UnitBuilder -> Unit : setHealth
UnitBuilder -> Unit : setStrength
end
GameMenu -> ComputerArmy : CreateArmy
loop 4 times
MyArmy-> Factory : createUnit
MyArmy -> Director : build
Director -> UnitBuilder : buildHealth
Director -> UnitBuilder : buildStrength
UnitBuilder -> Unit : setHealth
UnitBuilder -> Unit : setStrength
end

loop MyArmy size times
GameMenu -> MyArmy : getUnit
MyArmy -> Unit : getHealth
MyArmy -> Unit : getStrength
MyArmy -> Unit : getColor
end

loop ComputerArmy size times
GameMenu -> ComputerArmy : getUnit
ComputerArmy -> Unit : getHealth
ComputerArmy -> Unit : getStrength
ComputerArmy -> Unit : getColor
end

User ->  MyArmy : getUnit
User ->  ComputerArmy : getUnit...
User -> GameMenu : FightButton
Unit -> Unit : doAction

GameMenu -> ComputerArmy: getUnit
ComputerArmy -> Unit : getHealth

GameMenu -> ComputerArmy: getUnit
ComputerArmy -> Unit : getHealth
ComputerArmy -> Unit : getStrength
ComputerArmy -> Unit : getColor


ComputerArmy -> MyArmy : attack
Unit -> Unit : doAction

GameMenu -> MyArmy : getUnit
MyArmy -> Unit : getHealth

GameMenu -> MyArmy : getUnit
MyArmy -> Unit : getHealth
MyArmy -> Unit : getStrength
MyArmy -> Unit : getColor



@enduml